#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Sticker {
    ULB,
    UB,
    UBR,
    UL,
    U,
    UR,
    UFL,
    UF,
    URF,
    RFU,
    RU,
    RUB,
    RF,
    R,
    RB,
    RDF,
    RD,
    RBD,
    FLU,
    FU,
    FUR,
    FL,
    F,
    FR,
    FDL,
    FD,
    FRD,
    DLF,
    DF,
    DFR,
    DL,
    D,
    DR,
    DBL,
    DB,
    DRB,
    LBU,
    LU,
    LUF,
    LB,
    L,
    LF,
    LDB,
    LD,
    LFD,
    BRU, // bruh
    BU,
    BUL,
    BR,
    B,
    BL,
    BDR,
    BD,
    BLD,
}

// Order is important for index calculations

pub const EDGES: [(Sticker, Sticker); 12] = [
    (Sticker::DF, Sticker::FD),
    (Sticker::DB, Sticker::BD),
    (Sticker::DR, Sticker::RD),
    (Sticker::DL, Sticker::LD),
    (Sticker::BR, Sticker::RB),
    (Sticker::FR, Sticker::RF),
    (Sticker::FL, Sticker::LF),
    (Sticker::BL, Sticker::LB),
    (Sticker::UF, Sticker::FU),
    (Sticker::UB, Sticker::BU),
    (Sticker::UR, Sticker::RU),
    (Sticker::UL, Sticker::LU),
];

// Third sticker can be guessed from the first 2
pub const CORNERS: [(Sticker, Sticker); 8] = [
    (Sticker::DLF, Sticker::LFD),
    (Sticker::DBL, Sticker::BLD),
    (Sticker::ULB, Sticker::LBU),
    (Sticker::UFL, Sticker::FLU),
    (Sticker::DFR, Sticker::FRD),
    (Sticker::DRB, Sticker::RBD),
    (Sticker::UBR, Sticker::BRU),
    (Sticker::URF, Sticker::RFU),
];
